### PR TITLE
`camel case` problem when `xo` is used

### PR DESCRIPTION
**Pull request by CodeDotJS**
`npm test` will keep throwing `errror` if someone is using [xo](https://github.com/sindresorhus/xo) as a linter.

screenshot from 2016-06-18 01 12 00

To prevent it from above problem, I've done some changes and now `tests` are running throwing any `error`

### CODE REVIEW

**Comment by soyuka** [comment]
Hmm, yes but this is a BC break to me, also why don't you allow snake case on xo?

**Comment by CodeDotJS** [comment]
@soyuka 
Those who are using `xo` don't need camel_case type of thing in their code.

Now, following the "cultural" conventions it a good choice. I think `xo` provides that culture. 
Using ```camelCase``` and ```snake_case``` both in a same code is not a good idea. It will affect the beauty of the code.
I've read a lot of javascript code on github and I've not seen any developer using snake_case. 
Code style really matters.
Moreover, I read somewhere that camelCase is actually the easiest to read and type. 

So, this might be the main reason that developer chose a particular style instead or providing multiple choices.

**Comment by soyuka** [comment]
Ok, but I don't use xo. About "cultural" conventions, I don't agree that they should be a choice between `camelCase` and `snake_case`, but that's another debate.

If the PR doesn't break existing code, I'm willing to merge it. You could alias `snake_case` to `camelCase` instead of removing it. Anyway, your typehint script won't allow it either if I understood correclty?

**Comment by mitchellvanw** [comment]
I don't believe a library should force conventions, only a language should be able to do this. Code "beauty" and style is all subjective and in actuality, it truly shouldn't matter for the library. I consider this to be a bad design decision

**Comment by mitchellvanw** [comment]
I'm not sure about this, but it's probably even inefficient to enforce this.

**Comment by CodeDotJS** [comment]
> I don't believe a library should force conventions

@mitchellvanw have a look at [standard](https://github.com/feross/standard), which is created by feross.
It says "__One Style to Rule Them All__" and even the creator of web uses standard.

Standard don't allow us to use __semicolons__. So it doesn't mean that __it's a bad design decision__ and same thing goes for `xo` too. 

Now, If I'm using `xo` plus I've to use modules like `ansi-rainbow` and while running tests it's giving me error because author has used `snake_case` for identifiers, then what should I do? 
Should I ask developer of `xo` to provide `snake_case` option? Of course not! because I can do the small changes in my code to run successful tests. 

In this case, it's not possible to make the changes in my code. So, the best thing I can do is to make small changes in `module` so that the code can follow a proper style.

**Comment by CodeDotJS** [comment]
@soyuka 
Yes, it won't allow that too. 

And for `If the PR doesn't break existing code` : 
I did a successful test before submitting this PR. No breaks, no issues.

**Comment by soyuka** [comment]
> So, the best thing I can do is to make small changes in module so that the code can follow a proper style.

Your own proper style.

Btw, as long as you updated tests (and api), which are meant not to be changed while adding features, you're more likely to break existent implementations of ansi-rainbow in other modules. If I accept this PR, I'd have to realease a new major version, just because of 2 snake case usage in options.

**Comment by CodeDotJS** [comment]
C'mon man, how it will break existent implementations of ansi-rainbow in other modules?

I can simply update my ```package.json``` file for newer version or ignore if I don't want to. 
I'll have at least an option to use `color_space` and `colorSpace` depending upon the version I'm using.

**Comment by soyuka** [comment]
> C'mon man, how it will break existent implementations of ansi-rainbow in other modules?

I just have to release a major version for this change, because it changes the api for 1.x. When you change existent tests on a pull request, it often leads to BC breaks, here it's a fact. 

For example [this line](https://github.com/soyuka/thoughts-for-paris/blob/master/bin/thoughts-for-paris.js#L21) won't work anymore.

If this is really annoys you, feel free to publish your fork on npm and use it instead ;). I'm sorry but I can't justify myself to jump a major version just because some variable naming. Even if, it respects feross standards, which isn't the only standard btw, I really don't feel the need for this change.

**Comment by CodeDotJS** [comment]
Nothing annoying BTW.

> For example this line won't work anymore

It will work, unless and until you don't upgrade the version from `package.json` file.

No problem if you don't want to make changes. :)

**Comment by soyuka** [comment]
Extending global objects is never a good idea, I remember something just like this with shelljs (or another like this). 

It's possible to alias `snake_case` in `CamelCase` so that the linter doesn't break. You can't however remove `snake_case` from this library, for now. I'd accept such PR.

**Comment by CodeDotJS** [comment]
> It's possible to alias snake_case in CamelCase

 I tried, but it didn't worked. 

> for now. I'd accept such PR.

haha.. think you missed __not__

**Comment by soyuka** [comment]
Done, update to `1.0.1` to use aliased options.

**Comment by mitchellvanw** [comment]
@CodeDotJS It completely boggles my mind that, even though you had to go through all of this trouble to have another package update _it's proper code style_, you still think forcing a code style, which is completely optional, is a good idea.

Everyone's not obligated to use a certain code standard. I also truly don't care if the creator of the web uses a standard, hell, even the queen of england can use it. They aren't working in my codebase and their usage doesn't make me want to suddenly switch.

Also, _not using semicolons_ is a bad idea in JS. It's slower. Without semicolons the engine first has to analyse the code before running it, which is more expensive and less efficient.

We're talking about code style, btw. If XO didn't force this for some arbitrary reason there wouldn't any problems. XO created this bug. _That's bad design._

This is nuts.

**Pull request closed without merging**
